name: refuelety
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  logging: ^1.2.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  envied: ^0.5.4+1
  go_router: ^14.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
